exercism/clojure

- phone-number/phone_number_test.clj
Previous tests didn't force a fully generalized solution (for example: http://exercism.io/submissions/6cdc9ac426de4a28b9223a19a71717c1)
> Improve phone-number test suite

- grade-school/grade_school_test.clj
I just opened issue #41 about this. It's a pretty small fix, but the test seems broken to me. Hash maps don't maintain their order, so the comparison fails. This should fix that.
> Grade school sorted test now checks against a sorted map.

- bin/project.clj
The bin folder is not an exercise.  This commit removes a lein
configuration file that was incorrectly merged in by a previous pull
request.
> Remove lein config file from bin folder.

- bob/example.clj
The warnings were on Leiningen 2.5.1 on Java 1.8.0_45 OpenJDK 64-Bit Server VM:
call to static method isUpperCase on java.lang.Character can't be resolved (argument types: unknown).
call to static method isLowerCase on java.lang.Character can't be resolved (argument types: unknown).
> resolve warnings; use isLetter for readability

- .travis.yml
Setting sudo to false in the travis config will allow the travis tests
to run in travis' container based infrastructure and have faster start
times.
> Set sudo to false in travis config

- meetup/meetup_test.clj
Fixed an instance of the word 'map' which should have been 'may'
> Fix typo in meetup tests

- nucleotide-count/nucleotide_count_test.clj
This keeps backwards compatibility with existing solutions for nucleotide-count.
> Allows asserts in addition to exceptions.

- binary-search/binary_search_test.clj
- binary-search/example.clj
- binary-search/project.clj
- config.json
This adds the binary-search exercise to the clojure track. It includes
most of the tests from the ruby version as well as a couple of extras to
ensure the search works on lists as well as vectors. It also adds it to the
config.json in the first half of the clojure track.
> Add binary-search exercise

- binary-search/binary_search_test.clj
- binary-search/example.clj
If the tests for error cases care only that a Throwable is thrown, there is potential for false passes to occur.
For example, if the implementation of `binary-search/search-for` throws an IndexOutOfBoundsException for some input, the test will pass, even though there's actually just a bug in `binary-search/search-for`.
By checking for some message, we can be a little more confident that the tests are passing only for the correct exceptions.
Also, updated example.clj to pass the modified tests again.
> Use thrown-with-msg? in error case tests

- largest-series-product/example.clj
- largest-series-product/largest_series_product_test.clj
Clean up whitespace/line width and throw (and test for) an `Exception` when the given digit series is empty.
> Update largest-series-product per #49

- config.json
- octal/project.clj
- octal/src/example.clj
- octal/test/octal_test.clj
This exercise uses the implementation from the trinary exercise,
modified for the base of 8 instead of 3. The tests are ported from the
xruby exercise.
> Add octal exercise to clojure track

- triangle/src/example.clj
- triangle/test/triangle_test.clj
This PR will fix #95.
-----
Use empty lines between top-level forms.
Exclude `#'clojure.core/type` to avoid collision.
Make `#'triangle/type` point-free and ~2x faster.
If the sides are invalid, there's no need to compute the set. Unlike `cond`, `case` does a constant-time dispatch. Since we're effectively performing case analysis on `1` and `2` (constants), we might as well use `case` instead of `cond`. The point-free-ness of this change is both a matter of personal taste and "lazy" evaluation, i.e. don't compute unnecessary values.
The [previous solution]'s use of:
```clojure
(partition-by identity (sort [a b c]))
```
... is unnecessarily complex.
```clojure
(hash-set a b c)
```
... [gets the job done] more simply.
[1]: https://github.com/bbatsov/clojure-style-guide#empty-lines-between-t …
> Add (= :illogical (triangle/type 2 4 2)) test

- exercises/largest-series-product/src/example.clj
- exercises/largest-series-product/test/largest_series_product_test.clj
The digits and slices functions are internal implementation details and
thus the test case for the largest-series-product problem should not be
concerned with testing them. The series tests could potentially be moved
to the series exercise (which would have to be a new addition to this track)
Their presence may cause students to falsely think that their solution
has to use these two functions, instead of the alternative
implementation of only iterating through the digits once.
If it is desired to give hints on how to approach this problem (which
was one advantage of having the digits and slices tests), then consider
including a hints file and/or directory in the largest-series-product
directory.
This PR arises from discussion in
https://github.com/exercism/x-common/issues/192
> largest-series-product: Do not test digits/slices

- exercises/sum-of-multiples/src/example.clj
- exercises/sum-of-multiples/test/sum_of_multiples_test.clj
FIX #107 
REF exercism/x-common#198
> [sum-of-multiples] update tests to match common test data

- README.org
The attribution should be here, otherwise it will be very hard to find.
I don't use Emacs and from reading online, I understand absolutely nothing about Org-mode Markdown, so I just added it a different way.
a step in fixing https://github.com/exercism/exercism.io/issues/3112.
> attribute the clojure logo to its owner

- config.json
- exercises/all-your-base/project.clj
- exercises/all-your-base/src/all_your_base.clj
- exercises/all-your-base/src/example.clj
- exercises/all-your-base/test/all_your_base_test.clj
This commit adds the all-your-base exercise, with the tests ported from
the ruby version of the exercise.
> Add all-your-base exercise

- config.json
- exercises/bank-account/project.clj
- exercises/bank-account/src/example.clj
- exercises/bank-account/test/bank_account_test.clj
This PR re-adds the previous bank-account exercise with an updated
test suite. The previous test suite had a call to (shutdown-agents)
outside of a function body, which caused it to get called before all
tests had executed. This version of the test suite uses a fixture to
ensure that the (shutdown-agents) call happens *after* all tests have
executed.
> Re-add bank account

- config.json
- exercises/flatten-array/src/example.clj
- exercises/flatten-array/test/flatten_array_test.clj
This adds the flatten-array exercise, with tests based on the canonical
test data.
> Add flatten-array exercise

- exercises/robot-name/test/robot_name_test.clj
As per [this discussion](https://github.com/exercism/xclojure/issues/148), the tests didn't prevent you from hard-coding the new name in the `reset-name` function. This adds a new test to make sure you don't do that.
> Add test to robot-name to make sure name in reset isn't hard-coded (fixes #148)

- exercises/robot-name/src/example.clj
The original implementation seemed overly-complicated to me. This changes the example so that you generate the name when you generate the robot, rather than when you ask for its name.
> Simplify example implementation of robot-name

- exercises/robot-name/src/example.clj
This commit updates the generate-name function in robot-name to use
clojure's rand-int function instead of java interop. It also updates the
rand-int call to include all of the range 0-999 and refactors the string
assembly somewhat.
> Simplify generate-name function for robot-name

- .gitignore
- _src/clock_generator.clj
- _src/generator.clj
- config.json
- exercises/clock/clock.mustache
- exercises/clock/project.clj
- exercises/clock/src/example.clj
- exercises/clock/test/clock_test.clj
- project.clj
This commit adds a generator namespace, adds a stencil dependency, and
adds x-common to the .gitignore. When invoked, this will clone the
x-common repo if not present, then load and munge any test-data for the
passed exercise, and then render clojure tests using a mustache template
for the exercise.
> Add clojure test generator and clock exercise

- exercises/luhn/luhn.mustache
- exercises/luhn/src/example.clj
- exercises/luhn/test/luhn_test.clj
This PR should resolve https://github.com/exercism/xclojure/issues/159 by adding a test template for the luhn exercise and updating the example solution to pass the new tests.
> Update luhn and add luhn test template

- exercises/rotational-cipher/src/example.clj
- exercises/rotational-cipher/test/rotational_cipher_test.clj
A true rotational cipher does not care whether one rotates forwards or backwards.  The solution should be tested for this case.
> Test the cipher for opposite direction rotation.

- exercises/pangram/test/pangram_test.clj
The [problem spec](https://github.com/exercism/problem-specifications/blob/master/exercises/pangram/canonical-data.json) for Pangram specifically indicates that the characters will be all ASCII. Additionally, there was one test from the spec missing.
* Removed non-ascii test
* Added test for upper and lowercase characters not being counted separately
> Update tests to reflect master problem spec

- exercises/armstrong-numbers/test/armstrong_numbers_test.clj
The description contradicts what is being tested and needs to be in
the negative.
:heart:
> Fix 3-digit armstrong test description

- exercises/say/README.md
I really liked the challenge to use text-to-speech software to say the numbers out loud, but since the
README says "for Mac Users" I skimmed past it at first without paying attention. I'm glad I took
the time to find an alternative, and I wanted to make sure others will be made aware of it too, so I added a reference to espeak for Windows and Linux users.
> Say - Add referance to espeak

- exercises/isbn-verifier/test/isbn_verifier_test.clj
If your code verify the isbn length to be only *less than or equal to* 10, it will accept some ISBN with less than 10 digits which still satisfy other rules, being "00" a case which could be considered ISBN by some "almost correct" solutions missing this consideration.
I.e: http://exercism.io/submissions/f2fac1e79bf441e08afecd196ec0a442
> Add an ISBN Verifier test case for short ISBN

- exercises/anagram/src/anagram.clj
- exercises/armstrong-numbers/src/armstrong_numbers.clj
- exercises/beer-song/src/beer_song.clj
- exercises/bob/src/bob.clj
- exercises/clock/src/clock.clj
- exercises/collatz-conjecture/src/collatz_conjecture.clj
- exercises/etl/src/etl.clj
- exercises/flatten-array/src/flatten_array.clj
- exercises/grade-school/src/grade_school.clj
- exercises/hamming/src/hamming.clj
- exercises/leap/src/leap.clj
- exercises/nucleotide-count/src/nucleotide_count.clj
- exercises/phone-number/src/phone_number.clj
- exercises/reverse-string/src/reverse_string.clj
- exercises/rna-transcription/src/rna_transcription.clj
- exercises/robot-name/src/robot_name.clj
- exercises/run-length-encoding/src/run_length_encoding.clj
- exercises/say/src/say.clj
- exercises/series/src/series.clj
- exercises/sublist/src/sublist.clj
- exercises/two-fer/src/two_fer.clj
- exercises/word-count/src/word_count.clj
I added, or updated, default arguments in the first ~25 exercises' stub files. I tried to make the argument names input format and/or the scenario of the exercise, except in cases where it seemed completely redundant to do so (i.e. when a `num` really is just a `num`). Of course I'm open to feedback and will be happy to make changes as necessary.
> Add default args to stub files

- docs/RESOURCES.md
https://www.4clojure.com/ does not answer properly:
```
$ curl -v -k https://www.4clojure.com/
*   Trying 173.255.221.96...
* TCP_NODELAY set
* Connected to www.4clojure.com (173.255.221.96) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
* stopped the pause stream!
* Closing connection 0
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```
> updated link to 4Clojure in RESOURCES.md

- exercises/difference-of-squares/src/difference_of_squares.clj
- exercises/difference-of-squares/src/example.clj
- exercises/difference-of-squares/test/difference_of_squares_test.clj
In exercise "difference-of-sums", renamed `square-of-sums` to `square-of-sum` and `difference-of-sums` to `difference-of-squares`.
> difference-of-squares: renamed square-of-sums to square-of-sum

- exercises/proverb/src/example.clj
- exercises/proverb/src/proverb.clj
- exercises/proverb/test/proverb_test.clj
Proverb's test suite currently tests a single imported variable `proverb` to see if it matches the full text of the proverb, and does nothing else. The template for writing a solution doesn't even suggest that you use a function of any sort, simply giving you `(def proverb )`. This is inconsistent with both the README and the canonical test data for the exercise. I have corrected this problem, and look forward to submitting my updated solution.
> Redid Proverb Exercise

- config.json
The Clojure exercises are missing ratings. This isn't a great experience for users hoping to pick exercises appropriate to their level.
For a first pass at fixing this, I've copied ratings from other repos, (mainly the Elixir repo, as it's the closest language to Clojure that I can think of).
I'm sure it isn't perfect, but I think it's a decent first start, and that it's better than rating everything as 1.
Fixes https://github.com/exercism/clojure/issues/274
> Add exercise ratings

- exercises/reverse-string/test/reverse_string_test.clj
- single letter word test
- very long string test to encourage `reduce`, since a non-TCO recursive call will stack overflow.
> Add reverse-string tests

- config.json
Personally, I think that "armstrong numbers" is quite a difficult problem to be the very first one after "hello world"!
The first "real" problem in most other language tracks is "two-fer", and this seems about the right difficulty to me. 
I personally think the "reverse-string" and "bob" questions are a bit easier than "Armstrong numbers" as well which is why I have moved it down three spots below these three mentioned exercises. 
Go Clojureeeeeeeeeee! ❤️ 🔥 👍
> Reorder "Armstrong numbers" to be later in the queue

- exercises/phone-number/src/example.clj
- exercises/phone-number/test/phone_number_test.clj
README for the phone-number exercise specifies certain phone number digits as being 2-9, but the tests allow and use 0-9 for these digits.
Perhaps validating these digits conform is out of scope for these tests, but the tests are also written so that people who want to add these validations actually fail the tests.
> Fixing phone-number test cases

- exercises/concept/annalyns-infiltration/.meta/config.json
- exercises/concept/bird-watcher/.meta/config.json
- exercises/concept/cars-assemble/.meta/config.json
- exercises/concept/log-levels/.meta/config.json
- exercises/concept/lucians-luscious-lasagna/.meta/config.json
- exercises/concept/tracks-on-tracks-on-tracks/.meta/config.json
The authors and contributors of exercises are stored in an array of objects in the exercises' `.meta/config.json` files.
Each author/contributor used to have two properties: their GitHub username _and_ their Exercism username.
As we're only using the GitHub username, we're flattening the `authors` and `contributors` array to an array of strings representing the GitHub usernames.
We will update `configlet` to validate the new structure, so you might be seeing build failures once we've implemented this change. 
See https://github.com/exercism/docs/pull/90/files
We will automatically merge this PR immediately to be able to submit a different PR in which we'll add the authors/contributors for practice exercises.
https://github.com/exercism/v3-launch/issues/26
> 🤖 Flatten authors and contributors in .meta/config.json files

- concepts/lists/.meta/config.json
- config.json
_TL;DR; Add authors/contributors to a new `concepts/<slug>/.meta/config.json` to Concepts in the same way you have for Concept Exercises._
---
To properly attribute authorship/contributorship for an individual concept, each concept will have its own `.meta/config.json` file with `authors` and `contributors` keys like those for concept and practice exercises. We're also moving the concept's blurb from the track's `config.json` to the `.meta/config.json` file, also similar to concept and practice exercises.
See https://github.com/exercism/docs/pull/96/files for the update to the specification.
This PR adds a `.meta/config.json` file for all concepts found in the track's `config.json` file containing:
- A `blurb` key, which value is copied from the `config.json` file and subsequently removed …
> 🤖 Add .meta/config.json file for concepts

- config.json
> [v3] Add key features and tags

- config.json
To pass all linting checks (`./bin/configlet lint`), key features had to be trimmed down to max 100 characters.
> Pass linting checks

- .travis.yml
- _test/check_exercises.clj
Lint and lein test commands are failing on TraviCI. Fix them:
* Remove the unnecessary directory argument `.` to the `bin/configlet lint` command. Now it stills fails, but because the linter fails, not because the command is being called incorrectly. I decide to not fix the lint itself now since that'd require updating a lot of descriptions and which I have little knowledge or context of.
* Update `check-exercises` test, replacing it by `check-practice-exercises`. It was failing with `java.lang.IllegalArgumentException: Key must be integer` (see https://travis-ci.org/github/exercism/clojure/builds/774449427). Now it tests only practice tests, within the `/exercies/practice/` folder. Note that I tried to add a test for concept exercises as well but they do not use `lein` and I could not …
> Fix lint and lein test commands

- exercises/practice/queen-attack/test/queen_attack_test.clj
The current diagonal tests take place in a situation where the white piece is "to the left and above" the black piece, which means that a technically invalid solution, which does not properly consider all diagonal attack vectors, may pass all test cases.
Given the current test cases:
```clojure
(is (= true  (queen-attack/can-attack {:w [1 1] :b [6 6]})))
(is (= true  (queen-attack/can-attack {:w [0 6] :b [1 7]})))
(is (= true  (queen-attack/can-attack {:w [4 1] :b [6 3]})))
```
If we decompose `w` and `b` as `{[x1 y1] :w, [x2 y2] :b}`, then:
```
x1 <= x2
y1 <= y2
```
This commit adds two more valid diagonal test cases:
```clojure
(is (= true  (queen-attack/can-attack {:w [2 3] :b [5 0]})))
(is (= true  (queen-attack/can-attack {:w [2 3] :b [0 5]}))))
```
These will fail certain …
> Add two more diagonal test cases for queen attack

- config.json
With the updated version of the test runner that uses babashka, test runs finish in about 1 second. Quite an impressive feat!
> Update average test runner time

- exercises/concept/annalyns-infiltration/src/annalyns_infiltration.clj
- exercises/concept/annalyns-infiltration/test/annalyns_infiltration_test.clj
- exercises/concept/bird-watcher/src/bird_watcher.clj
- exercises/concept/bird-watcher/test/bird_watcher_test.clj
- exercises/concept/cars-assemble/src/cars_assemble.clj
- exercises/concept/cars-assemble/test/cars_assemble_test.clj
- exercises/concept/interest-is-interesting/src/interest_is_interesting.clj
- exercises/concept/interest-is-interesting/test/interest_is_interesting_test.clj
- exercises/concept/international-calling-connoisseur/src/dialing_codes.clj
- exercises/concept/international-calling-connoisseur/test/dialing_codes_test.clj
- exercises/concept/log-levels/src/log_levels.clj
- exercises/concept/log-levels/test/log_levels_test.clj
- exercises/concept/lucians-luscious-lasagna/src/lucians_luscious_lasagna.clj
- exercises/concept/lucians-luscious-lasagna/test/lucians_luscious_lasagna_test.clj
- exercises/concept/squeaky-clean/src/squeaky_clean.clj
- exercises/concept/squeaky-clean/test/squeaky_clean_test.clj
- exercises/concept/tracks-on-tracks-on-tracks/src/tracks_on_tracks_on_tracks.clj
- exercises/concept/tracks-on-tracks-on-tracks/test/tracks_on_tracks_on_tracks_test.clj
We previously simplified the Concept exercises' directory structure but never changed the namespaces in the source/test files, which is causing the tests to fail. This fixes that.
> Fix namespaces to match directory structure

- exercises/concept/lucians-luscious-lasagna/test/lucians_luscious_lasagna_test.clj
The tests were failing because there was an error in the test! The `expected-time` unit test was trying to call a number as a function.
> Fix faulty unit test

- exercises/concept/annalyns-infiltration/test/annalyns_infiltration_test.clj
- exercises/concept/bird-watcher/test/bird_watcher_test.clj
- exercises/concept/cars-assemble/test/cars_assemble_test.clj
- exercises/concept/interest-is-interesting/test/interest_is_interesting_test.clj
- exercises/concept/log-levels/test/log_levels_test.clj
- exercises/concept/lucians-luscious-lasagna/test/lucians_luscious_lasagna_test.clj
- exercises/practice/acronym/test/acronym_test.clj
- exercises/practice/allergies/test/allergies_test.clj
- exercises/practice/beer-song/test/beer_song_test.clj
- exercises/practice/robot-name/test/robot_name_test.clj
- exercises/practice/robot-simulator/test/robot_simulator_test.clj
- exercises/practice/rotational-cipher/test/rotational_cipher_test.clj
- exercises/practice/sublist/test/sublist_test.clj
- exercises/practice/triangle/test/triangle_test.clj
As a quick fix for the test runner not handling some tests properly (see https://github.com/exercism/clojure/issues/420 and https://github.com/exercism/clojure/issues/421), I decided to simply rewrite the tests to suit the runner. Every `is` assertion in this PR has been wrapped within its own `deftest` so it will be properly reported on the website.
The real fix is this: https://github.com/exercism/clojure-test-runner/issues/22 but it's taking a bit longer and this will at least get the user experience working right.
> Make test suites conform to test runner expected input

- exercises/practice/triangle/test/triangle_test.clj
A few dashes were missing in a test name, causing the specs to error out. This PR fixes that.
> Fix typos in spec

- config.json
* Had too many exercises practicing `numbers` and `strings`. Narrowed it down to ones that I thought were "definitely exercises in `x`".
* Added `international-calling-connoisseur` and `squeaky-clean` to `config.json` with a `status` of `wip`, since their directories and WIP contents exist.
> Fix linting errors

- config.json
- exercises/concept/interest-is-interesting/.meta/exemplar.clj
- exercises/concept/interest-is-interesting/src/interest_is_interesting.clj
- exercises/concept/interest-is-interesting/test/interest_is_interesting_test.clj
Fixes: #428 and #430. When porting this exercise I noticed some arithmetic discrepancies and wrongly assumed they were due to minor differences in the way the JVM and CLR handle decimals. Turns out I was doing something wrong, and fortunately this was brought to my attention so I could fix it before this exercise confuses many more people :P
> Correct BigDecimal arithmetic

- exercises/concept/elyses-destructured-enchantments/.docs/instructions.md
Part 3, "Swap the first two cards", can't be solved with destructuring alone, yet the instructions suggest otherwise.
If someone is up for the challenge, please try it, but even @porkostomus (author) used `vec` and `conj` :) 
https://exercism.org/tracks/clojure/exercises/elyses-destructured-enchantments/solutions/porkostomus
> docs(elyses): remove misleading instruction

- exercises/concept/tracks-on-tracks-on-tracks/.meta/config.json
Perhaps the first contribution of many. And perhaps the only one that is only about one character :). 
Typo: `abouts` should be `about`. #459  
I'm assuming pull requests go to `main`. If not, I'd love to learn otherwise.
> Typo: `abouts` > `about`

- exercises/concept/tracks-on-tracks-on-tracks/src/tracks_on_tracks_on_tracks.clj
With the default order, the "conj" function wouldn't behave well. Also, for consistency, as all other functions have "lang-list" as first argument.
> reverse the order of args in add-language function

- test.clj
CI has been failing since features were added to the test runner and I believe it was related to a conditional development workflow in `test.clj` that doesn't belong there anyway. It was remaining from when I developed the CI script and it was actually preventing a proper integration test with the `clojure-test-runner` repo as was intended. This change simply hardcodes the `root` and `test-runner-dir` locations to where they are in prod.
> remove dev workflow

- .github/workflows/test.yml
- test.clj
Upgraded the babashka Docker action to the one currently maintained by the community.
> Temporary patch to get CI working again

- exercises/concept/bird-watcher/.docs/hints.md
- exercises/concept/interest-is-interesting/.docs/hints.md
- exercises/concept/log-levels/.docs/hints.md
Hints were not being rendered because I forgot to add hyphens. Apparently the spec requires them to be an unordered list.
> Add hyphens to fix hints

- exercises/practice/nth-prime/src/nth_prime.clj
Not sure if this one specifically wants the missing arg to be included by the user, but until this exercise, all had the args filled, so I think maintaining consistency should be desired here.
> Improves `nth-prime` scaffold

- exercises/concept/tracks-on-tracks-on-tracks/.docs/instructions.md
Use thread-last in list-add test to match Task 2
example:
Task 2 Add a new language to the list example:
```clojure
(add-language "JavaScript" '("Clojurescript"))
;; => '("JavaScript" "Clojurescript")
```
Fails Test 2 list-add-test
Thread-first would work if the parameters were switched. What is the intended argument order?
```clojure
;; Current test depends on this parameter order
(defn add-language [lang-list lang]
(conj lang-list lang))
;; Example gives this parameter order
(defn add-language [lang lang-list]
(conj lang-list lang))
```
> test: fix list-add test

- exercises/practice/sublist/test/sublist_test.clj
I noticed some solutions to the sublist exercise that look like this:
```clojure
(ns sublist
(:require [clojure.set :as s]))
(defn classify [list1 list2]
(cond
(= list1 list2) :equal
(s/subset? list1 list2) :sublist
(s/subset? list2 list1) :superlist
:else :unequal))
```
This solution passes all the tests but, doesn't work correctly in many cases:
```clojure
(classify [1] [2 3]) ;; should be :unequal
;; => :sublist
(classify [3 4 5] [3 4]) ;; should be :superlist
;; => :unequal
```
This PR adds a test that fails on solutions that use the set module functions this way.
> Add test case to sublist exercise failing incorrect use of set operations

- exercises/concept/annalyns-infiltration/test/annalyns_infiltration_test.clj
- exercises/concept/bird-watcher/test/bird_watcher_test.clj
- exercises/concept/cars-assemble/test/cars_assemble_test.clj
- exercises/concept/date-parser/test/date_parser_test.clj
- exercises/concept/elyses-destructured-enchantments/test/elyses_destructured_enchantments_test.clj
- exercises/concept/interest-is-interesting/test/interest_is_interesting_test.clj
- exercises/concept/international-calling-connoisseur/test/international_calling_connoisseur_test.clj
- exercises/concept/log-levels/test/log_levels_test.clj
- exercises/concept/lucians-luscious-lasagna/test/lucians_luscious_lasagna_test.clj
- exercises/concept/squeaky-clean/test/squeaky_clean_test.clj
- exercises/concept/tracks-on-tracks-on-tracks/test/tracks_on_tracks_on_tracks_test.clj
This PR is an updated version of #434
Sorry for creating a new PR, but I don't have permission to push my changes directly to the existing branch and couldn't see another way.
What I've done:
1. Rebased the existing #434 branch on top of main (since it was quite old) and resolved the merge conflicts
2. Updated the metadata format to match what the test runner will support once exercism/clojure-test-runner#43 is merged
3. Added task metadata to the tests for the only 2 exercises that have task numbers but didn't have metadata yet. I think both are still WIP exercises but doesn't hurt to add the metadata anyway
> Add task-test metadata v2

- exercises/shared/.docs/representations.md
This PR adds a file to be displayed to mentors to explain what normalizations occur during the representation process.
> Publish representation guidance notes

- exercises/practice/largest-series-product/.docs/instructions.md
- exercises/practice/largest-series-product/.docs/introduction.md
- exercises/practice/largest-series-product/.meta/tests.toml
- exercises/practice/largest-series-product/test/largest_series_product_test.clj
The largest-series-product exercise has been overhauled as part of a project to make practice exercises more consistent and friendly.
For more context, please see the discussion in the forum, as well as the pull request that updated the exercise in the problem-specifications repository:
- https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943
- https://github.com/exercism/problem-specifications/pull/2246 
Note that we have deprecated and removed two test cases that deal with the multiplicative identity (also referred to as an empty product). By doing this we were able to avoid talking about this at all, which makes this exercise much more approachable.
----
If you approve this pull request, I will eventually merge it. However, if …
> Sync largest-series-product docs with problem-specifications

- docs/INSTALLATION.md
- exercises/practice/hello-world/.docs/instructions.append.md
Also included, by request, instructions for installing the Leiningen tool.
Linux: added instructions for LinuxBrew, bumped Clojure version
Mac: Added instructions for installing Temurin Java
Windows: Include new PowerShell installer
Also included a bit for common editor/IDE plugins.
Added instructions for testing with the Clojure CLI on the `hello-world` page.
> update installation instructions for Linux, Mac and Windows

- exercises/concept/cars-assemble/.docs/introduction.md
`<>` inequality operator doesn't seem to exist in Clojure, replaced it with `not=`
> cars-assemble: Update introduction.md

- exercises/concept/lucians-luscious-lasagna/.docs/introduction.md
Briefly explained Clojure's syntax for defining and calling functions, and pointed out how it immediately differs from other Lisps.
Simplified example function call and added evaluation output in code comments
> Improve explanation of function syntax

- exercises/practice/robot-name/.meta/src/example.clj
- exercises/practice/robot-name/test/robot_name_test.clj
The instructions state:
> Your solution must ensure that every existing robot has a unique name.
However, there was not any test to ensure that the solution satisfies this.
> Add unit test to robot name

- concepts/strings/links.json
The old URL (http://clojure-doc.org/articles/cookbooks/strings.html) returns a 404. This updates the URL to the current location of the docs.
> Fix URL for clojure-docs page about strings

- exercises/concept/interest-is-interesting/.meta/exemplar.clj
- exercises/concept/interest-is-interesting/project.clj
- exercises/concept/interest-is-interesting/src/interest_is_interesting.clj
Clojure 1.11 added an `abs` function that we can now use instead of defining our own function or `Math/abs`.
I've also replaced the TODO in docstrings. This is just a copy-paste from the problem description. Feel free to edit them if needed.
> Interest is interesting: Update exemplar solution to use built-in function abs from Clojure 1.11

- exercises/concept/squeaky-clean/.docs/instructions.md
- exercises/concept/squeaky-clean/test/squeaky_clean_test.clj
The string "my\0Id" works fine in Java, but isn't parsed at all in Clojure. I've replaced it with a proper unicode sequence.
Another thing i've noticed is that some people use something like `#"\p{Cntrl}"` as a regex that cleans the control chars. This regex looks fine, but it's not. It covers the first range `u0000-\u001F` and only the first char from the second range `\u007F-\u009F`. Obviously those people didn't even consider the possibility of that regex not covering everything.
Should we replace the control char in tests with a different one? If so, i'll do it in this PR.
> Squeaky clean: Use different control chars

- exercises/practice/complex-numbers/.docs/instructions.md
- exercises/practice/complex-numbers/.meta/tests.toml
- exercises/practice/complex-numbers/test/complex_numbers_test.clj
Partially addresses #520 
Tests are now in sync, missing tests have been implemented, order of the actual and expected results has been fixed.
I'll try to address the issue with the floats in a subsequent PR since this one is changes a lot of things.
> Complex numbers: Sync tests with problem-specifications

- exercises/practice/complex-numbers/test/complex_numbers_test.clj
Closes #520 
In the division operation, the user usually needs to force a conversion to float or double just to pass the tests. This is no longer a requirement. With this commit the Ratio type is also allowed. So instead of typing something like
```
(defn div
[[a b] [c d]]
(let [denom (float (+ (* c c) (* d d)))]
[(/ (+ (* a c) (* b d)) denom)
(/ (- (* b c) (* a d)) denom)]))
```
we can now safely remove the explicit `float` conversion and allow for a wider range of solutions.
At the same time, the new tests convert all double to float. A check like  `(= 2.5 2.4999999999999996)`, which returns false, becomes `(= (float 2.5) (float 2.4999999999999996))` and this returns true. So by lowering the required accuracy, the issue of a correct solution failing due to floating point inaccuracies is …
> Complex numbers: Allow Ratio type in division

- exercises/practice/phone-number/.docs/instructions.md
- exercises/practice/phone-number/.meta/config.json
- exercises/practice/phone-number/.meta/tests.toml
- exercises/practice/phone-number/src/phone_number.clj
- exercises/practice/phone-number/test/phone_number_test.clj
Closes #230 
Synced and non-required functions were removed from phone-number.clj
Tests were insufficient, so broken solutions are expected. The example solution still works fine though.
> Phone number: Sync with problem-specifications

- exercises/practice/armstrong-numbers/.docs/instructions.md
- exercises/practice/armstrong-numbers/.meta/config.json
- exercises/practice/armstrong-numbers/.meta/tests.toml
- exercises/practice/armstrong-numbers/test/armstrong_numbers_test.clj
The updated tests from problem specifications require solutions that use big integers. While this can be easily done in Clojure, those tests were left out to avoid breaking existing solutions.
> Armstrong numbers: Sync with problem-specifications

- config.json
I'm really going to miss typing that one. /s
Whose idea was it to name it that, anyway?
The lists exercise, Tracks... was problematic for three reasons:
1. The entire exercise except for the final task involved writing functions that did nothing but wrap clojure core functions like `first`, `last`, etc.
2. The final task really had nothing to do with lists but rather involved function composition. It also could not be ergonomically solved without using a threading macro which the student would not presumably know at that point.
3. It has an unreasonably long name.
This exercise is considerably harder, but puts the lists concept ahead in the syllabus because it has conditionals and booleans as prerequisites.
> Activate Card Games exercise, deprecate Tracks on Tracks on Tracks

- config.json
Fixes #550.
Prerequisites for Bank Account changed to "conditionals" and "numbers", which matches what other tracks have selected for this exercise.
Even that might be overkill, because the Clojure solution actually requires neither of those...
For reference, here is the example solution:
```clojure
(defn open-account []
(atom 0))
(defn close-account [acct]
(reset! acct nil))
(defn get-balance [acct]
@acct)
(defn update-balance [account amount]
(swap! account + amount))
```
Still, I think it's probably appropriate to have *some* prerequisites to prevent the student from encountering this exercise too early, before they would reasonably be introduced to atoms, which don't yet have a concept exercise. In any case, this is an improvement because the exercise *definitely* has nothing to do …
> Change Bank Account prerequisites/practices

- exercises/concept/cars-assemble/test/cars_assemble_test.clj
A simple fix for the issue described below:
https://forum.exercism.org/t/cant-solve-cars-assemble-because-of-floating-point-precision/9242
The current tests check if two double numbers x, y are equal, and as a result some of them are failing when the numbers aren't identical. Two possible solutions: 
* Check if the two numbers are close enough using a check like `abs(x-y)<epsilon`.
* Truncate doubles to floats. This lowers the required precision required for the tests to pass.
This PR employs the second approach.
> Cars-assemble: fix tests failing due to floating point precision

- exercises/practice/binary-search/.docs/instructions.md
- exercises/practice/binary-search/.meta/config.json
- exercises/practice/binary-search/.meta/src/example.clj
- exercises/practice/binary-search/test/binary_search_test.clj
As mentioned here
http://forum.exercism.org/t/48in24-exercise-07-02-binary-search/11462/6
@ErikSchierboom
> Binary search: Sync metadata docs, implement tests, update example solution

- exercises/practice/space-age/.docs/instructions.md
- exercises/practice/space-age/.docs/introduction.md
- exercises/practice/space-age/.meta/config.json
- exercises/practice/space-age/.meta/tests.toml
For #48in24
Sync docs, metadata, tests
The existing implementation of the tests uses a separate function for each planet, but the last test (unknown planet as input) in canonical data implies that there should be only one function for all tests. Changing the tests to reflect that will break all solutions, so at this point, i decided to just mark the test as excluded.
> space-age: Sync

- exercises/practice/protein-translation/.docs/instructions.md
- exercises/practice/protein-translation/.meta/tests.toml
- exercises/practice/protein-translation/test/protein_translation_test.clj
For #48in24
https://forum.exercism.org/t/48in24-exercise-02-13-protein-translation/9556
> protein-translation: Sync

- exercises/practice/accumulate/.meta/tests.toml
- exercises/practice/collatz-conjecture/.meta/tests.toml
@ErikSchierboom, mark this as `rep/tiny` if you could. These edits don't touch the tests themselves so we shouldn't rerun solutions if possible.
I'll follow up with PRs for several other slugs that do need updates to the tests.
> Add missing tests.toml files for accumulate and collate-conjecture

- exercises/concept/card-games/.docs/introduction.md
Fix a minor error in the introduction to the Card Games exercise
> card-games: fix typo

- exercises/practice/say/.docs/instructions.md
- exercises/practice/say/.meta/config.json
- exercises/practice/say/.meta/tests.toml
- exercises/practice/say/test/say_test.clj
Also closes #302, as the 'extensions' section mentioned in #302 no longer exists in the synced version.
> say: Sync with problem specifications

- exercises/concept/bird-watcher/.docs/hints.md
- exercises/concept/bird-watcher/.meta/exemplar.clj
The hints for task 4 mention `every?`, `pos?`, and `not`. However, the exemplar solution is `(pos? (count (filter zero? birds)))`, which is not only different, but also suboptimal. This PR updates the solution to `(not (every? pos? birds))` to align with the hints.
I’ve also replaced the `last` function with `peek` since this exercise deals exclusively with vectors, and `peek` is the recommended way to retrieve the last element of a vector.
> bird-watcher: Update exemplar solution

- exercises/practice/complex-numbers/.docs/instructions.append.md
Adding an instructions.append to clarify that the exponent function isn't required.
Original thread:
https://forum.exercism.org/t/remove-mention-of-exponentiation-from-instructions/13225
> complex-numbers: Clarify that the exponent function isn't required

- exercises/concept/squeaky-clean/.docs/hints.md
- exercises/concept/squeaky-clean/.docs/instructions.md
This PR primarily fixes incorrect references to functions from the `clojure.string` namespace, such as `string/join`.
Additionally, I've edited and reworded certain parts to improve flow and maintain consistency.
Edit: In the third commit, the word 'need' was replaced to make it clearer that what follows are only suggestions.
> squeaky-clean: Update docs

- exercises/concept/annalyns-infiltration/.docs/hints.md
- exercises/concept/annalyns-infiltration/.docs/instructions.md
- exercises/concept/annalyns-infiltration/.docs/introduction.md
This PR primarily fixes an issue with an incorrect hint. It should explicitly state `true` instead of 'truthy'.
Edit: Changed 'that' to 'which', given the context (adding extra detail about something already clear)
Edit: Changed 'if' to 'whether', given the context (presenting two implied alternatives)
> annalyns-infiltration: Update docs

- exercises/practice/kindergarten-garden/.meta/tests.toml
- exercises/practice/kindergarten-garden/test/kindergarten_garden_test.clj
Sync and complete rewrite of all tests.
Coming up with appropriate names for each `deftest` is nearly impossible for this exercise since the test descriptions are overly long, and some tests are nested three levels deep. So, I just used the `test-<uuid>` naming convention proposed in [issue #673](https://github.com/exercism/clojure/issues/673).
I also used one `deftest` per test, as suggested in the aforementioned issue.
**Note:** There are multiple issues with the error messages when >1 tests are placed under a single `deftest`. I'll open an issue about that soon in the test runner repo.
> kindergarten-garden: Sync tests

- exercises/concept/bird-watcher/.docs/introduction.md
Small fix in an example that can't be evaluated.
I am not sure if could be better move the example to:
```clojure
(def three-values [4 5 6])
```
as the exercise is presented in part of the Numbers path... What do you thing?
> bird-watcher: Fix introduction example

- config.json
- exercises/practice/eliuds-eggs/.docs/instructions.md
- exercises/practice/eliuds-eggs/.docs/introduction.md
- exercises/practice/eliuds-eggs/.meta/config.json
- exercises/practice/eliuds-eggs/.meta/src/example.clj
- exercises/practice/eliuds-eggs/.meta/tests.toml
- exercises/practice/eliuds-eggs/deps.edn
- exercises/practice/eliuds-eggs/project.clj
- exercises/practice/eliuds-eggs/src/eliuds_eggs.clj
- exercises/practice/eliuds-eggs/test/eliuds_eggs_test.clj
This is one of the [48in24 exercises](https://forum.exercism.org/t/48in24-exercise-11-05-eliuds-eggs/12900/3)
> Add Eliud's eggs exercise

- config.json
- exercises/practice/list-ops/.docs/instructions.append.md
- exercises/practice/list-ops/.meta/config.json
- exercises/practice/list-ops/.meta/src/example.clj
- exercises/practice/list-ops/.meta/src/example_lists.clj
- exercises/practice/list-ops/src/list_ops.clj
- exercises/practice/list-ops/test/list_ops_test.clj
Since the exercise deals with vectors, I've added it as extra prerequisite.
There's one more change needed (split into one deftest per test) so I'm marking it as draft.
> Publish list-ops

- config.json
Since **'All your base'** has been implemented, the following exercises are marked as deprecated:
1. Binary
2. Trinary
3. Octal
4. Hexadecimal
I've also deprecated **'accumulate'** since **'list-ops'** will be published soon. Therefore, I'm marking the current PR as draft. It will be merged after https://github.com/exercism/clojure/pull/685
> Deprecate exercises

- exercises/practice/sublist/.docs/instructions.append.md
- exercises/practice/sublist/.docs/instructions.md
- exercises/practice/sublist/.meta/config.json
- exercises/practice/sublist/.meta/tests.toml
- exercises/practice/sublist/src/sublist.clj
- exercises/practice/sublist/test/sublist_test.clj
Also
* Added instructions append to clarify the input type
* Updated starter file sublist.clj (changed lists references to colls)
> sublist: Sync with problem specifications

- exercises/practice/list-ops/.docs/instructions.append.md
* Standardize the first paragraph in the append file
* Update the wording in both goals
> list-ops: Update instructions append

- exercises/practice/armstrong-numbers/.meta/config.json
- exercises/practice/armstrong-numbers/.meta/src/example.clj
- exercises/practice/armstrong-numbers/.meta/tests.toml
- exercises/practice/armstrong-numbers/src/armstrong_numbers.clj
- exercises/practice/armstrong-numbers/test/armstrong_numbers_test.clj
Added the final two tests involving big integers. Without these tests, some solutions improperly relied on Java interop for exponentiation, which is incorrect since Java's exponentiation functions return floating-point numbers instead of integers, as required here. Additionally, without these tests, incorrect solutions using Java interop could pass all tests. This PR addresses both issues.
Also
* Updated the armstrong_numbers.clj starter file with a proper function template
* Explicitly check with `true?` and `false?` as `true` and `false` are the exact values expected to be returned by `armstrong?`
* Updated example solution to pass the new tests
> armstrong-numbers: Include excluded tests

- concepts/lists/.meta/config.json
- concepts/lists/about.md
- concepts/lists/links.json
Quick update for the lists concept
* `cons` isn't used to add elements to the beginning of a list. This is a job for `conj`. Therefore, `cons` has been completely removed.
* `conj` does not append items to a list; it prepends them (adds to the beginning). This has been clarified.
* Added links to all functions
* Updated links.json
> Update lists concept

- exercises/practice/minesweeper/.meta/config.json
- exercises/practice/minesweeper/.meta/tests.toml
- exercises/practice/minesweeper/src/minesweeper.clj
- exercises/practice/minesweeper/test/minesweeper_test.clj
Also
* Refactored and simplified all existing tests
* Marked the first test as excluded so that it's in sync with the implemented tests
> minesweeper: Implement tests

- bin/verify-exercises
- bin/verify-exercises-in-docker
@tasxatzial This PR adds the missing verify script(s)
https://github.com/exercism/clojure/pull/718 should be merged first
> Add scripts to verify exercises

- exercises/practice/matching-brackets/.meta/config.json
- exercises/practice/matching-brackets/src/matching_brackets.clj
- exercises/practice/matching-brackets/test/matching_brackets_test.clj
Made the tests consistent by explicitly checking with `true?` as well, as `true` is the other value expected to be returned by `valid?`
> matching-brackets: Explicitly check with true? in tests

- exercises/practice/armstrong-numbers/test/armstrong_numbers_test.clj
- exercises/practice/dominoes/test/dominoes_test.clj
- exercises/practice/kindergarten-garden/test/kindergarten_garden_test.clj
- exercises/practice/list-ops/test/list_ops_test.clj
- exercises/practice/minesweeper/test/minesweeper_test.clj
- exercises/practice/pythagorean-triplet/test/pythagorean_triplet_test.clj
- exercises/practice/spiral-matrix/test/spiral_matrix_test.clj
- exercises/practice/sublist/test/sublist_test.clj
- exercises/practice/word-count/test/word_count_test.clj
No more uuids in test functions (removed only from already merged PRs)
Also test descriptions in Clojure tests are now identical to the descriptions in their corresponding .toml files.
> Remove uuids from test functions

- exercises/practice/difference-of-squares/.meta/config.json
- exercises/practice/difference-of-squares/.meta/tests.toml
- exercises/practice/difference-of-squares/src/difference_of_squares.clj
- exercises/practice/difference-of-squares/test/difference_of_squares_test.clj
Also updated the difference_of_squares.clj starter file with a proper function template
> difference-of-squares: Sync tests

- exercises/practice/gigasecond/.meta/tests.toml
- exercises/practice/gigasecond/src/gigasecond.clj
- exercises/practice/gigasecond/test/gigasecond_test.clj
Also
* Updated the gigasecond.clj starter file with a proper function template
* Specs mention that some tests check only for date (not time), which appears to be the case in the existing implementation. Therefore, the tests that also check time were marked as excluded.
* Removed the commented out test since it's not part of the specs.
> gigasecond: Sync tests

- exercises/practice/pangram/.meta/config.json
- exercises/practice/pangram/.meta/tests.toml
- exercises/practice/pangram/src/pangram.clj
- exercises/practice/pangram/test/pangram_test.clj
Also
* Updated the pangram.clj starter file with a proper function template
* Explicitly test with `true?` as well, as `true` is the other value expected to be returned by `pangram?`
> pangram: Sync tests

- exercises/practice/atbash-cipher/.meta/config.json
- exercises/practice/atbash-cipher/.meta/example.clj
- exercises/practice/atbash-cipher/.meta/tests.toml
- exercises/practice/atbash-cipher/src/atbash_cipher.clj
- exercises/practice/atbash-cipher/test/atbash_cipher_test.clj
Last two decode tests have been marked as not implemented because the inputs are not valid encoded strings. They should be removed from the specs as well.
https://forum.exercism.org/t/atbash-cipher-are-the-last-two-tests-invalid/13482
Also, this update will invalidate all solutions, as the old tests did not even include the decoding part of the exercise.
> atbash-cipher: Sync tests with problem specifications

- bin/add-practice-exercise
This should be merged after #728 is merged.
> Update add-practice-exercise script to reference test generator

- docs/GENERATORS.md
- docs/config.json
This should be merged after https://github.com/exercism/clojure/pull/728 is merged.
> Add generator docs

- bin/update-practice-exercise
This should make it easier to update an exercise
> Add script to update practice exercise

- exercises/practice/two-fer/.meta/generator.tpl
- exercises/practice/two-fer/src/two_fer.clj
- exercises/practice/two-fer/test/two_fer_test.clj
Should be merged after https://github.com/exercism/clojure/pull/728 is merged
> two-fer: add generator and regenerate tests

- exercises/practice/roman-numerals/.meta/generator.tpl
- exercises/practice/roman-numerals/.meta/tests.toml
- exercises/practice/roman-numerals/src/roman_numerals.clj
- exercises/practice/roman-numerals/test/roman_numerals_test.clj
Should be merged after https://github.com/exercism/clojure/pull/728 is merged
> roman-numerals: add generator and regenerate tests

- exercises/practice/isogram/.meta/generator.tpl
Should be merged _after_ https://github.com/exercism/clojure/pull/728 is merged
> isogram: add generator template

- generators/deps.edn
This must be caused by a dependency using this library
> Fix warning about slf4j not being available

- exercises/practice/wordy/.meta/config.json
- exercises/practice/wordy/.meta/example.clj
- exercises/practice/wordy/.meta/generator.clj
- exercises/practice/wordy/.meta/generator.tpl
- exercises/practice/wordy/src/wordy.clj
- exercises/practice/wordy/test/wordy_test.clj
This demonstrates how easy it is to handle errors
> wordy: update to latest

- exercises/practice/largest-series-product/.meta/config.json
- exercises/practice/largest-series-product/.meta/example.clj
- exercises/practice/largest-series-product/.meta/generator.clj
- exercises/practice/largest-series-product/.meta/generator.tpl
- exercises/practice/largest-series-product/.meta/tests.toml
- exercises/practice/largest-series-product/src/largest_series_product.clj
- exercises/practice/largest-series-product/test/largest_series_product_test.clj
Taking a stab at this. One thing that concerns me a bit is the type of Exception thrown. Right now all of them are marked as IllegalArgument, but perhaps not all of them should. In particular, a span that has length 5 and a string "123" will throw Exception even both of them are valid as individual arguments. It's just the combination that isn't valid.
@ErikSchierboom Any ideas?
> largest-series-product: Sync tests

- docs/GENERATORS.md
- exercises/practice/change/test/change_test.clj
- exercises/practice/largest-series-product/test/largest_series_product_test.clj
- exercises/practice/saddle-points/test/saddle_points_test.clj
- exercises/practice/simple-cipher/test/simple_cipher_test.clj
- exercises/practice/wordy/test/wordy_test.clj
- generators/deps.edn
- generators/src/formatting.clj
- generators/src/templates.clj
I've been using [cljfmt](https://github.com/weavejester/cljfmt) lately and it has been really helpful getting my code formatted nicely. This PR is an experiment to see what happens if we use that library to auto format our generated templates.
The benefits are:
- Consistent style amongst exercises
- Templates become less of a hassle when trying to fix whitespace and do alignment (to me, these have been _the_ most annoying things when building templates)
The main downside is that you would have to adhere to the style used by cljfmt. We _could_ add support to opt-out of auto-formatting, but it would have to be the exception I feel.
> Auto format rendered templates

- exercises/practice/acronym/.meta/generator.tpl
- exercises/practice/anagram/.meta/generator.tpl
- exercises/practice/armstrong-numbers/.meta/generator.tpl
- exercises/practice/change/.meta/generator.tpl
- exercises/practice/darts/.meta/generator.tpl
- exercises/practice/difference-of-squares/.meta/generator.tpl
- exercises/practice/high-scores/.meta/generator.tpl
- exercises/practice/isbn-verifier/.meta/generator.tpl
- exercises/practice/isogram/.meta/generator.tpl
- exercises/practice/largest-series-product/.meta/generator.tpl
- exercises/practice/leap/.meta/generator.tpl
- exercises/practice/matrix/.meta/generator.tpl
- exercises/practice/pangram/.meta/generator.tpl
- exercises/practice/pig-latin/.meta/generator.tpl
- exercises/practice/resistor-color-duo/.meta/generator.tpl
- exercises/practice/resistor-color/.meta/generator.tpl
- exercises/practice/reverse-string/.meta/generator.tpl
- exercises/practice/roman-numerals/.meta/generator.tpl
- exercises/practice/saddle-points/.meta/generator.tpl
- exercises/practice/scrabble-score/.meta/generator.tpl
- exercises/practice/simple-cipher/.meta/generator.tpl
- exercises/practice/square-root/.meta/generator.tpl
- exercises/practice/sum-of-multiples/.meta/generator.tpl
- exercises/practice/triangle/.meta/generator.tpl
- exercises/practice/twelve-days/.meta/generator.tpl
- exercises/practice/two-fer/.meta/generator.tpl
- exercises/practice/wordy/.meta/generator.tpl
- exercises/practice/yacht/.meta/generator.tpl
- exercises/practice/zebra-puzzle/.meta/generator.tpl
- generators/src/templates.clj
This is possible due to the use of cljfmt _after_ rendering the template.
I feel that less use of `~` makes it easier to read, as well as being able to separate multiple loops in a single template by a blank line.
> Simplify templates

- generators/src/formatting.clj
- generators/src/templates.clj
This attempts to separate formatting code from template rendering code a bit. Let me know what you think
> Move formatting code to formatting namespace

- exercises/practice/series/.meta/config.json
- exercises/practice/series/.meta/example.clj
- exercises/practice/series/.meta/generator.clj
- exercises/practice/series/.meta/generator.tpl
- exercises/practice/series/.meta/tests.toml
- exercises/practice/series/src/series.clj
- exercises/practice/series/test/series_test.clj
The order of argument checks regarding error cases is from the first argument to last (first argument is checked, if it does not throw error, then the second argument is checked and so on)
Edit: This applies only to the example solution. There are no test cases where both arguments result in an error.
> series: Sync tests

- exercises/practice/hamming/.meta/config.json
- exercises/practice/hamming/.meta/example.clj
- exercises/practice/hamming/.meta/generator.clj
- exercises/practice/hamming/.meta/generator.tpl
- exercises/practice/hamming/src/hamming.clj
- exercises/practice/hamming/test/hamming_test.clj
The current tests were returning `nil` for strands of unequal length. Admittedly, `nil` is one of the trickiest parts of the language, but this looks like an incorrect use of `nil` to me. I've replaced them with Exceptions but will revert if there's any disagreement.
> hamming: Sync tests

- exercises/practice/matching-brackets/.meta/generator.tpl
- exercises/practice/matching-brackets/src/matching_brackets.clj
- exercises/practice/matching-brackets/test/matching_brackets_test.clj
Last test had an extra `\` for each `\`, this has now been fixed.
> matching-brackets: Add generator and regenerate tests

- exercises/practice/binary-search/.docs/instructions.append.md
- exercises/practice/binary-search/.meta/example.clj
- exercises/practice/binary-search/.meta/generator.clj
- exercises/practice/binary-search/.meta/generator.tpl
- exercises/practice/binary-search/.meta/tests.toml
- exercises/practice/binary-search/src/binary_search.clj
- exercises/practice/binary-search/test/binary_search_test.clj
* Changed to return -1 instead of some kind of error when value is not in the vector
* Updated function template
> binary-search: Update tests

- exercises/practice/list-ops/.meta/generator.clj
- exercises/practice/list-ops/.meta/generator.tpl
- exercises/practice/list-ops/test/list_ops_test.clj
Trimmed the parent descriptions so that they only contain the function names found in the docs.
> list-ops: Add generators and regenerate tests

- exercises/practice/allergies/.meta/generator.clj
- exercises/practice/allergies/.meta/generator.tpl
- exercises/practice/allergies/test/allergies_test.clj
[no important files changed]
While `(safe-str (keyword "eggs"))` results in `:eggs` in final test file, when mapping over arrays the result looks like this
```
[
#object[com.github.jknack.handlebars.Handlebars$SafeString 0x135f160e ":eggs"]
#object[com.github.jknack.handlebars.Handlebars$SafeString 0x230e163b ":shellfish"]
]
```
Not sure how i could make this work, i switched to a different approach with `symbol` and without `safe-str`:
`#(symbol (str (keyword %)))`
does seem to do the trick.
@ErikSchierboom Thoughts or suggestions?
> allergies: add generators and regenerate tests

- exercises/concept/squeaky-clean/deps.edn
Tests fail to run with current deps.edn when using the test alias or exercism test.
> Fix test runner alias - update deps.edn for squeaky-clean

- exercises/shared/.docs/tests.md
Forum topic https://forum.exercism.org/t/help-md-testing-in-repl-without-leiningen-fails/18529
This removes the instructions for running tests from REPL for two reasons:
1. They don't seem to work when using the Clojure CLI
2. They don't offer any advantage over the other existing test methods
If we ever have a section in the docs about using the REPL for development, we can add them back and potentially expand them. For now, it's safe to remove them.
> Remove REPL test-running instructions from shared docs
