exercism/clojure

- config.json
- docs/INSTALLATION.md
- docs/WORKFLOW.md
And here goes Clojure documentation.
> Adding track specific documentation.

- beer-song/beer_song_test.clj
> Test for verse-0

- beer-song/example.clj
Feel free to reject. Not sure what the purpose is of these examples but some of us currently feel this version is easier to grok than the other approach which uses many conditionals just to avoid data duplication.
> fewer conditionals --> clearer code

- rna-transcription/example.clj
no need to use seq, every?, set, let ... no need to repeat hash lookup
> simpler code

- bank-account/bank_account_test.clj
The main thing here is that the usage of `pcall` was incorrect. `pcall` takes a variable number of functions, not forms, and returns a lazy list, which must be evaluated to guarantee that all the calls are complete.
> Fixes pcalls, and cleans up tests with a macro.

- config.json
- hello-world/example.clj
- hello-world/hello_world_test.clj
- hello-world/project.clj
For https://github.com/exercism/todo/issues/24
> Created hello-world exercise

- SETUP.md
> Adding instructions to SETUP.md

- queen-attack/example.clj
- queen-attack/queen_attack_test.clj
> Update queen attack

- config.json
- pascals-triangle/example.clj
- pascals-triangle/pascals_triangle_test.clj
- pascals-triangle/project.clj
This adds a pascal's triangle exercise to the clojure track.
> Add Pascal's Triangle exercise

- docs/ABOUT.md
- docs/RESOURCES.md
Updates documentation for `ABOUT.MD` & `RESOURCES.MD`.
[Addresses issue #82](https://github.com/exercism/xclojure/issues/82)
> Add ABOUT.md and update RESOURCES.md

- largest-series-product/src/example.clj
- largest-series-product/test/largest_series_product_test.clj
As part of the work to have consistency between tracks as in https://github.com/exercism/todo/issues/104 and https://github.com/exercism/todo/issues/13. Comments are in individual commit messages.
> largest-series-product corner cases

- exercises/binary-search/src/example.clj
- exercises/binary-search/test/binary_search_test.clj
> Remove check for sorted input from binary-search

- README.org
- SETUP.org
- docs/ABOUT.org
- docs/INSTALLATION.org
- docs/LEARNING.org
- docs/RESOURCES.org
- docs/TESTS.org
- Titles
- Punctuation
- Capitalization
- Links
- `s/1.7.0/1.8.0/g`
- `src`/`example` blocks
- Whitespace/wrapping
- Headings
> Miscellaneous normalization

- docs/INSTALLATION.org
Hi this is my first open source contribution -- This should fix a broken link to clojure's download page.
> broken link clojure download fix

- exercises/hello-world/HINTS.md
- exercises/hello-world/src/hello_world.clj
This will make sure newcomers know where the code goes.
I am not sure if this is how we should do it. But I see other languages doing the same [eg. javascript](https://github.com/exercism/xjavascript/blob/master/exercises/bob/bob.js). Let me know if this will work and I will add stubs for other exercises. Not sure if we should do this for all exercises or few initial ones. I don't see ruby/javascript doing it for all. 
Also we should have something like this for `hello-world` https://github.com/exercism/xjavascript/blob/master/exercises/hello-world/HINTS.md
> Add a stub exercise file to hello_world

- config.json
- exercises/bracket-push/project.clj
- exercises/bracket-push/src/example.clj
- exercises/bracket-push/test/bracket_push_test.clj
> Add bracket-push

- exercises/anagram/src/anagram.clj
- exercises/bob/src/bob.clj
- exercises/rna-transcription/src/rna_transcription.clj
- exercises/word-count/src/word_count.clj
Hello world was already added in #122, add to next 4 exercises (to make it 5). 
I guess these would be enough.
Fixes #121
> Add some more stubs files for exercises

- _test/check_exercises.clj
- config.json
> replace 'problems' key with 'exercises' in config.json

- config.json
- exercises/perfect-numbers/project.clj
- exercises/perfect-numbers/src/example.clj
- exercises/perfect-numbers/test/perfect_numbers_test.clj
This adds the perfect-numbers exercise, with tests borrowed from the
ruby implementation.
> Add perfect-numbers exercise

- exercises/flatten-array/project.clj
Unsure if this is 100% correct.  Just copied from another file and changed a few choice phrases to `flatten-array`.
> Create flatten-array project.clj

- exercises/binary-search/test/binary_search_test.clj
Seems to be leftover from #113
> Remove unsorted-vector variable

- config.json
- exercises/pig-latin/project.clj
- exercises/pig-latin/src/example.clj
- exercises/pig-latin/test/pig_latin_test.clj
I've created some tests using the sample data at https://github.com/exercism/x-common/blob/master/exercises/pig-latin/canonical-data.json and have added an example solution.
> Added pig-latin exercise

- config.json
- exercises/nth-prime/project.clj
- exercises/nth-prime/src/example.clj
- exercises/nth-prime/test/nth_prime_test.clj
This adds the nth-prime exercise with tests from x-common.
> Add nth-prime exercise

- config.json
- exercises/secret-handshake/project.clj
- exercises/secret-handshake/src/example.clj
- exercises/secret-handshake/test/secret_handshake_test.clj
Adding the secret handshake exercise.
This is my first exercism exercise submission, not sure if I have everything right.
Also, still new to Clojure so the example isn't great :smile:
> secret handshake exercise

- config.json
- exercises/sublist/project.clj
- exercises/sublist/src/example.clj
- exercises/sublist/sublist.mustache
- exercises/sublist/test/sublist_test.clj
This PR takes a PR from @leetwinski and refactors it some, also adds a test generator template for the sublist exercise.
Should resolve #161.
> Add Sublist exercise

- exercises/kindergarten-garden/src/example.clj
The main fix I wanted to fix is to use clojure.string/lower-case rather than the Java method, as that is more idiomatic in this case. But I also did some formatting fixes.
> Garden fixes

- exercises/flatten-array/src/example.clj
Use tree-seq for readability and efficiency, re: my comment in #138.
> Use tree-seq in flatten-array.

- config.json
- exercises/rotational-cipher/project.clj
- exercises/rotational-cipher/src/example.clj
- exercises/rotational-cipher/test/rotational_cipher_test.clj
Added the rotational-cipher puzzle with tests and solution.
https://github.com/exercism/x-common/blob/master/exercises/rotational-cipher/description.md
> Add rotational-cipher puzzle with tests and solution.

- config.json
- exercises/collatz-conjecture/README.md
- exercises/collatz-conjecture/project.clj
- exercises/collatz-conjecture/src/collatz_conjecture.clj
- exercises/collatz-conjecture/src/example.clj
- exercises/collatz-conjecture/test/collatz_conjecture_test.clj
It was on the Unimplemented exercises of [exercism.io](http://exercism.io) so i decided to implement it.
> adding collatz-conjecture

- config.json
- exercises/series/README.md
- exercises/series/project.clj
- exercises/series/src/example.clj
- exercises/series/src/series.clj
- exercises/series/test/series_test.clj
another Unimplemented exercise.
> adding series

- exercises/beer-song/src/beer_song.clj
As discussed in #199.
The stub is a bit more... fleshed out than the other ones, but I guess that's okay given that it's basically the minimal amount of code to run the test suite without exceptions.
> Add beer_song.clj stub

- config.json
- exercises/two-fer/README.md
- exercises/two-fer/project.clj
- exercises/two-fer/src/example.clj
- exercises/two-fer/src/two_fer.clj
- exercises/two-fer/test/two_fer_test.clj
Add two-fer to clojure track as per [todo](http://exercism.io/languages/clojure/todo)
> two-fer: add to track

- config.json
- exercises/say/README.md
- exercises/say/project.clj
- exercises/say/src/example.clj
- exercises/say/src/say.clj
- exercises/say/test/say_test.clj
Add `say` exercise to clojure track
> say: add to track

- config.json
- exercises/two-fer/README.md
- exercises/two-fer/project.clj
- exercises/two-fer/src/example.clj
- exercises/two-fer/src/two_fer.clj
- exercises/two-fer/test/two_fer_test.clj
This reverts commit 0850d77eb68e226437458495b365a34c145f32f8.
###	config.json - resolved
> Revert "revert two-fer"

- exercises/hello-world/src/example.clj
- exercises/hello-world/test/hello_world_test.clj
This fixes https://github.com/exercism/clojure/issues/215
> Fix hello world

- exercises/bob/README.md
- exercises/bob/src/example.clj
- exercises/bob/test/bob_test.clj
This commit updates the bob exercise to take into account the shouting
question case, which involves updating the readme, test, and example
solution.
> Issue #214: Update bob for ambiguous case

- config/maintainers.json
This commit updates maintainers.json to show haus on the website.
> Update maintainers.json: show haus on website

- exercises/proverb/src/example.clj
- exercises/proverb/test/proverb_test.clj
Solves #254.
The README shows last line as "And all for the want of a nail.".
The test requires the last line to be "And all for the want of a horseshoe nail.".
> Proverb: align the test with README.

- exercises/bob/README.md
- exercises/change/README.md
- exercises/complex-numbers/README.md
- exercises/crypto-square/README.md
- exercises/dominoes/README.md
- exercises/gigasecond/README.md
- exercises/go-counting/README.md
- exercises/hamming/README.md
- exercises/hello-world/README.md
- exercises/two-fer/README.md
- exercises/wordy/README.md
Update out of date READMEs using `configlet`
> Update READMEs using configlet

- exercises/reverse-string/README.md
I just noticed we are not actually mentioning to not use `reverse` there, even if it's even in the community solutions (and the exercise doesn't really make sense using just `reverse`).
> add a restriction for reverse

- config.json
This commit adds a blurb to config.json to briefly explain what Clojure is.
> Add blurb to config.json (addresses #265)

- .travis.yml
- exercises/armstrong-numbers/src/example.clj
this brings the reference impl more inline with the mentor notes.
> update armstrong reference impl

- exercises/nucleotide-count/src/example.clj
- exercises/nucleotide-count/src/nucleotide_count.clj
- exercises/nucleotide-count/test/nucleotide_count_test.clj
> fix function name collision exercism#253

- exercises/leap/test/leap_test.clj
Added more tests for the 'Leap' exercise (based on the problem specifications)
> Update tests for 'Leap' exercise

- exercises/armstrong-numbers/test/armstrong_numbers_test.clj
Hi, this PR is an update to `armstrong-numbers` to update the unit test to match the [problem specifications](https://github.com/exercism/problem-specifications/blob/master/exercises/armstrong-numbers/canonical-data.json) version `1.1.0`
I'm still learning Clojure, so any suggestions would be helpful!
Thanks!
> Updates armstrong-numbers to 1.1.0

- exercises/reverse-string/test/reverse_string_test.clj
Hi, this PR is an update to `reverse-string` to update the unit test to match the[ problem specifications](https://github.com/exercism/problem-specifications/blob/master/exercises/reverse-string/canonical-data.json) version 1.2.0
I'm still learning Clojure, so any suggestions would be welcomed!
Thanks!
> Updates reverse-string to 1.2.0

- exercises/bob/src/example.clj
- exercises/bob/test/bob_test.clj
Hi, this PR is an update to `bob` to update the unit test to match the[ problem specifications](https://github.com/exercism/problem-specifications/blob/master/exercises/bob/canonical-data.json) version 1.4.0
I'm still learning Clojure, so any suggestions would be welcomed!
Thanks!
> Updates bob to 1.4.0

- config/maintainers.json
Hi, as requested adding myself in the maintainer json file for clojure, thank you~
> - In order to get into the correct teams, and get the correct permissions set, we need you to PR your details to the config/maintainers.json file in the track repository (The file is at https://github.com/exercism/$SLUG/blob/master/config/maintainers.json). Please set show_on_website: false
> add new maintainer

- exercises/triangle/src/example.clj
- exercises/triangle/src/triangle.clj
- exercises/triangle/test/triangle_test.clj
Updated tests based on the problem specifications. Also updated the example.
> Update tests for 'Triangle' exercise

- exercises/practice/grade-school/.docs/instructions.md
- exercises/practice/phone-number/test/phone_number_test.clj
Fixes #345 
Fixes #347 
I'm still learning the ropes, sorry for any mistakes
> phone-number: redefined var / grade-school: tiny typo

- exercises/practice/crypto-square/.meta/src/example.clj
- exercises/practice/crypto-square/test/crypto_square_test.clj
The current implementation did not follow the spec. In this commit, the tests are updated as well as the example implementation.
Closes #372
> Fix crypto-square exercise

- exercises/practice/hello-world/src/hello_world.clj
Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46
> 🤖 Simplify `hello-world` stub

- config.json
Fixes: https://github.com/exercism/clojure/issues/294#issue-676417114
Added tags to topics header in config.json.
> Improve tags/topics for exercises

- exercises/practice/two-fer/project.clj
Closes https://github.com/exercism/exercism/issues/5671
> Update two-fer to clojure 1.10.0

- docs/LEARNING.md
- docs/RESOURCES.md
> Fix 4clojure links

- config.json
I think this might be the last step to get them live.
> Flip Concept exercises from "wip" to "beta"

- config.json
Follow-up of #401, if you want it.
> Disable concept exercises

- config.json
I feel like I'm throwing darts now, but maybe this? The exercises are still locked on the website for me. I thought setting concept exercises back to false would prevent them from blocking progress.
> Set concept exercises to "wip"

- concepts/vectors/about.md
- concepts/vectors/introduction.md
- exercises/concept/bird-watcher/src/bird_watcher.clj
Page still contains embarrassing TODO comment, and it shows the answer to the student. SPOILER ALERT!!
> Fix bird-watcher exercise

- concepts/lists/introduction.md
I noticed a few minors issues in the copy for the introduction and thought I would help with some improvements.
> Spelling and grammar improvements

- exercises/concept/tracks-on-tracks-on-tracks/test/tracks_on_tracks_on_tracks_test.clj
> Complete exercise test suite

- exercises/concept/annalyns-infiltration/project.clj
- exercises/concept/bird-watcher/project.clj
- exercises/concept/cars-assemble/project.clj
- exercises/concept/interest-is-interesting/project.clj
- exercises/concept/international-calling-connoisseur/project.clj
- exercises/concept/log-levels/project.clj
- exercises/concept/lucians-luscious-lasagna/project.clj
- exercises/concept/tracks-on-tracks-on-tracks/project.clj
Within an hour after launching Concept exercises we received issue #413 from someone trying to use the CLI with Leiningen. That makes me very happy, so we'll now include a `project.clj` as well!
> add lein config to concept exercises

- exercises/concept/tracks-on-tracks-on-tracks/src/tracks_on_tracks_on_tracks.clj
Hello,
Was running the exercises and found that this step comment was different from the expected.
> Matching exercise description.

- exercises/practice/queen-attack/.meta/src/example.clj
- exercises/practice/robot-name/test/robot_name_test.clj
* A recent update to the `queen-attack` tests caused the example solution to fail. I replaced it with a new implementation which passes.
* A unit test in `robot-name` had an error in it.
> Fix failing exercises

- concepts/vectors/about.md
- exercises/concept/bird-watcher/.docs/introduction.md
Fix a small typo in the concept about/exercise introduction for vectors
> Fix typo in introduction

- exercises/practice/sublist/.docs/instructions.md
I find it really difficult to understand what was asked in the exercice sublist.
It's not really clear what the function should return.
I improved the instructions.
> Update instructions.md for exercice sublist

- exercises/concept/lucians-luscious-lasagna/src/lucians_luscious_lasagna.clj
> Add brief notice to explain differences with Clojure

- exercises/practice/change/.meta/src/example.clj
- exercises/practice/change/test/change_test.clj
Hi, I think this would be a worthwhile addition to the tests because it requires more elaborate checks inside the solution algorithm.
> Clojure/change: Add new test for invalid amount/coins combination

- exercises/concept/cars-assemble/.docs/instructions.md
> Clarify `cars-assemble` instructions

- exercises/practice/acronym/src/acronym.clj
> Improves `acronym` scaffold

- concepts/strings/links.json
This is a quick PR to fix issue #513.  Should be fine after this.
If possible adding a `hacktoberfest-accepted` tag would be nice.
> Broken Link Fix

- exercises/concept/cars-assemble/test/cars_assemble_test.clj
This is a very simple test name correction.
> Correct test name

- exercises/concept/elyses-destructured-enchantments/test/elyses_destructured_enchantments_test.clj
> Fix assertion argument order in Elyses Destructured Enchantments tests

- concepts/chars/.meta/config.json
- concepts/chars/about.md
- concepts/chars/introduction.md
- concepts/chars/links.json
- config.json
- exercises/concept/squeaky-clean/.docs/hints.md
- exercises/concept/squeaky-clean/.docs/instructions.md
- exercises/concept/squeaky-clean/.docs/introduction.md
- exercises/concept/squeaky-clean/.meta/exemplar.clj
- exercises/concept/squeaky-clean/test/squeaky_clean_test.clj
Pretty sure I'm still missing things.
> Add Squeaky clean in beta mode

- concepts/chars/.meta/config.json
- concepts/chars/about.md
- concepts/chars/introduction.md
- exercises/concept/squeaky-clean/.docs/instructions.md
- exercises/concept/squeaky-clean/project.clj
- exercises/concept/squeaky-clean/test/squeaky_clean_test.clj
Added `project.clj`.
Also some of the task numbers were incorrect.
> Add Leiningen config (project.clj)

- exercises/concept/interest-is-interesting/.docs/hints.md
See: https://forum.exercism.org/t/clojure-track-hints/6209
> Add task numbers to hints

- exercises/concept/squeaky-clean/.docs/introduction.md
Added an example interop call and a link to the Clojure reference on Java interop.
> Improve squeaky-clean introduction

- exercises/practice/rotational-cipher/.docs/instructions.md
- exercises/practice/rotational-cipher/test/rotational_cipher_test.clj
Closes #506 
Sync docs and tests.
> Rotational cipher: Sync with problem-specifications

- exercises/practice/robot-simulator/.docs/instructions.md
- exercises/practice/robot-simulator/src/robot_simulator.clj
- exercises/practice/robot-simulator/test/robot_simulator_test.clj
Closes #456 
Complete re-write of tests. Took way longer than expected because I wasn't able to decide what's the most appropriate way to write them. So, i just picked the one that looked best to me.
> Robot simulator: Sync with problem-specifications

- exercises/concept/card-games/.docs/hints.md
I forgot to put the numbers in the hints to match the instructions
> Fix Card Games hints

- concepts/atoms/.meta/config.json
- concepts/atoms/about.md
- concepts/atoms/introduction.md
- concepts/atoms/links.json
- concepts/closures/.meta/config.json
- concepts/closures/about.md
- concepts/closures/introduction.md
- concepts/closures/links.json
- config.json
- exercises/concept/coordinate-transformation/.docs/hints.md
- exercises/concept/coordinate-transformation/.docs/instructions.md
- exercises/concept/coordinate-transformation/.docs/introduction.md
- exercises/concept/coordinate-transformation/.meta/config.json
This exercise teaches closures and atoms, and adds those concepts to the concepts directory.
> Add Coordinate Transformation learning exercise

- exercises/practice/anagram/.meta/tests.toml
- exercises/practice/anagram/test/anagram_test.clj
Update tests for #48in24
https://forum.exercism.org/t/48in24-exercise-07-23-anagram/11584
> anagram: Sync tests

- exercises/practice/matching-brackets/.meta/tests.toml
- exercises/practice/matching-brackets/test/matching_brackets_test.clj
For #48in24
https://forum.exercism.org/t/48in24-exercise-06-18-matching-brackets/11396
> matching-brackets: Sync tests

- exercises/practice/pig-latin/.docs/instructions.md
For #48in24
https://forum.exercism.org/t/48in24-exercise-05-28-pig-latin/11343
> pig-latin: Sync docs

- exercises/practice/allergies/.docs/instructions.md
- exercises/practice/allergies/.meta/config.json
- exercises/practice/allergies/.meta/src/example.clj
- exercises/practice/allergies/.meta/tests.toml
- exercises/practice/allergies/test/allergies_test.clj
For #48in24
https://forum.exercism.org/t/48in24-exercise-03-19-allergies/9928
**Edit:** Example solution was also updated so that it passes the new tests
> allergies: Sync

- exercises/practice/luhn/.docs/instructions.md
- exercises/practice/luhn/.meta/config.json
- exercises/practice/luhn/.meta/src/example.clj
- exercises/practice/luhn/.meta/tests.toml
- exercises/practice/luhn/test/luhn_test.clj
For #48in24
https://forum.exercism.org/t/48in24-exercise-04-02-luhn/10467
Example solution was updated so that it passes the new tests
> luhn: sync

- exercises/practice/scrabble-score/test/scrabble_score_test.clj
For #48in24
https://forum.exercism.org/t/48in24-exercise-04-09-scrabble-score/10468
Exercise is already in sync. This PR implements the tests
> scrabble-score: Implement tests

- exercises/concept/interest-is-interesting/.docs/instructions.md
greater or equal than -> greater than or equal to
> Fix typos in interest-is-interesting instructions

- exercises/concept/card-games/.docs/hints.md
Also slightly reworded for consistency.
> card-games: Fix broken links in hints

- exercises/practice/rna-transcription/test/rna_transcription_test.clj
Implementing tests to address the problem described here:
https://forum.exercism.org/t/confusing-message-about-a-test-failure-while-still-accepting-solution/13254
> rna-transcription: Implement tests

- config.json
- exercises/concept/card-games/.meta/config.json
- exercises/concept/coordinate-transformation/.meta/config.json
- exercises/practice/yacht/.meta/config.json
- exercises/practice/zipper/.meta/config.json
The result of running `bin/configlet fmt -y -u`
> Format files

- exercises/practice/dominoes/.meta/config.json
- exercises/practice/dominoes/.meta/tests.toml
- exercises/practice/dominoes/src/dominoes.clj
- exercises/practice/dominoes/test/dominoes_test.clj
Also
* Updated the dominoes.clj starter file with a proper function template
* Rewritten tests so that they are simpler and consistent.
> dominoes: Sync tests

- exercises/practice/complex-numbers/.docs/instructions.append.md
- exercises/practice/complex-numbers/.docs/instructions.md
Also standardize the intro in the append file
> complex-numbers: Sync docs

- exercises/concept/annalyns-infiltration/.docs/hints.md
- exercises/concept/annalyns-infiltration/.docs/instructions.md
* Formatting into one sentence per line
* Various grammar fixes, such as splitting overly long sentences into two, using American spelling, and rewording to improve readability, consistency, and clarity
> annalyns-infiltration: Update docs

- exercises/practice/word-count/.meta/config.json
- exercises/practice/word-count/.meta/src/example.clj
- exercises/practice/word-count/.meta/tests.toml
- exercises/practice/word-count/src/word_count.clj
- exercises/practice/word-count/test/word_count_test.clj
The addition of the extra tests will most likely break most solutions. The previous two example solutions were also broken, so a new solution had to be written.
Also
* Updated the word_count.clj starter file with a proper function template
> word-count: Sync tests

- exercises/practice/eliuds-eggs/.docs/instructions.append.md
Clearing up some confusion that may arise from the instructions.
> eliuds-eggs: Add instructions append

- exercises/practice/allergies/.docs/instructions.append.md
- exercises/practice/allergies/.meta/config.json
- exercises/practice/allergies/src/allergies.clj
- exercises/practice/allergies/test/allergies_test.clj
Also
* Updated the allergies.clj starter file with proper function templates
* Added instructions append to clarify the output type
> allergies: Split into one deftest per test

- exercises/practice/yacht/.meta/tests.toml
- exercises/practice/yacht/src/yacht.clj
- exercises/practice/yacht/test/yacht_test.clj
Also
* Updated the yacht.clj starter file with a proper function template
* Added the missing .toml file
> yacht: Split into one deftest per test

- exercises/practice/etl/.meta/config.json
- exercises/practice/etl/src/etl.clj
- exercises/practice/etl/test/etl_test.clj
Implemented missing tests, removed outdated ones, and made all tests uniform.
> etl: Implement tests

- test.clj
> Fix incorrect status being returned

- exercises/practice/leap/.meta/generator.tpl
- exercises/practice/leap/src/leap.clj
- exercises/practice/leap/test/leap_test.clj
> leap: update to latest

- exercises/practice/triangle/.meta/generator.tpl
- exercises/practice/triangle/.meta/tests.toml
- exercises/practice/triangle/src/triangle.clj
- exercises/practice/triangle/test/triangle_test.clj
> triangle: update to latest

- exercises/practice/armstrong-numbers/.meta/generator.tpl
No changes were made to the tests when running the generator.
> armstrong-numbers: add generator

- exercises/practice/isbn-verifier/.meta/generator.tpl
Running the generator did not cause any changes to the test file
> isbn-verifier: add generator

- exercises/practice/sublist/.docs/instructions.append.md
Removing the last sentence of the append file, as it doesn't seem to serve any purpose and might confuse readers.
(it's me who added this in the first place...)
> sublist: Update instructions append

- docs/GENERATORS.md
- generators/src/templates.clj
This is the most common transformation so I thought: let's optimize for it.
> Add individual test case transform exit point

- exercises/practice/anagram/.meta/config.json
- exercises/practice/armstrong-numbers/.meta/config.json
- exercises/practice/difference-of-squares/.meta/config.json
- exercises/practice/isbn-verifier/.meta/config.json
- exercises/practice/isogram/.meta/config.json
- exercises/practice/leap/.meta/config.json
- exercises/practice/pangram/.meta/config.json
- exercises/practice/roman-numerals/.meta/config.json
- exercises/practice/sum-of-multiples/.meta/config.json
- exercises/practice/triangle/.meta/config.json
- exercises/practice/two-fer/.meta/config.json
Forgot to add myself to the contributors list
> Add `erikschierboom` as contributor

- exercises/practice/anagram/.meta/generator.tpl
- exercises/practice/armstrong-numbers/.meta/generator.tpl
- exercises/practice/darts/.meta/generator.tpl
- exercises/practice/difference-of-squares/.meta/generator.tpl
- exercises/practice/high-scores/.meta/generator.clj
- exercises/practice/high-scores/.meta/generator.tpl
- exercises/practice/isbn-verifier/.meta/generator.tpl
- exercises/practice/isogram/.meta/generator.tpl
- exercises/practice/leap/.meta/generator.tpl
- exercises/practice/matrix/.meta/generator.tpl
- exercises/practice/pangram/.meta/generator.tpl
- exercises/practice/resistor-color/.meta/generator.tpl
- exercises/practice/roman-numerals/.meta/generator.tpl
- exercises/practice/scrabble-score/.meta/generator.tpl
- exercises/practice/square-root/.meta/generator.tpl
- exercises/practice/sum-of-multiples/.meta/generator.clj
- exercises/practice/sum-of-multiples/.meta/generator.tpl
- exercises/practice/triangle/.meta/generator.tpl
- exercises/practice/two-fer/.meta/generator.tpl
Once this is merged, I'll do a PR to change `transform` to `transform-test-case` where applicable
> Simplify templates

- exercises/practice/reverse-string/.meta/config.json
- exercises/practice/reverse-string/.meta/example.clj
- exercises/practice/reverse-string/.meta/generator.tpl
- exercises/practice/reverse-string/.meta/tests.toml
- exercises/practice/reverse-string/src/reverse_string.clj
- exercises/practice/reverse-string/test/reverse_string_test.clj
Also,
* Updated example solution
* Updated function template
* Excluded the two grapheme tests:
* They would invalidate all solutions
* They would invalidate all approaches
* I wasn't able to come up with a simple solution that passed those tests.
> reverse-string: Add generator and regenerate tests

- exercises/practice/high-scores/test/high_scores_test.clj
- exercises/practice/resistor-color/test/resistor_color_test.clj
- exercises/practice/triangle/test/triangle_test.clj
- exercises/practice/twelve-days/test/twelve_days_test.clj
- generators/src/templates.clj
> Update description separator to `▶`

- exercises/practice/pig-latin/.meta/config.json
- exercises/practice/pig-latin/.meta/generator.tpl
- exercises/practice/pig-latin/.meta/tests.toml
- exercises/practice/pig-latin/src/pig_latin.clj
- exercises/practice/pig-latin/test/pig_latin_test.clj
Using `▶` as separator between parent/child descriptions. Will update if needed before merging.
> pig-latin: Sync tests

- config.json
- exercises/practice/change/.meta/config.json
- exercises/practice/change/.meta/example.clj
- exercises/practice/change/.meta/generator.clj
- exercises/practice/change/.meta/generator.tpl
- exercises/practice/change/.meta/tests.toml
- exercises/practice/change/src/change.clj
- exercises/practice/change/test/change_test.clj
This was a tough one. I got some practice with generator.clj functions. I also had to update the example solution, so I 'cheated' by copying one of the community solutions since I haven't solved it myself.
> change: Sync tests

- exercises/practice/rna-transcription/.meta/config.json
- exercises/practice/rna-transcription/.meta/example.clj
- exercises/practice/rna-transcription/.meta/generator.tpl
- exercises/practice/rna-transcription/src/rna_transcription.clj
- exercises/practice/rna-transcription/test/rna_transcription_test.clj
Second time i'm updating this. In the first update there used to be some kind of error checking in the tests that wasn't present in the specs. I updated the tests, now it's a good time to simplify the example solution as well.
> rna-transcription: Add generators and regenerate tests

- exercises/practice/eliuds-eggs/.meta/generator.tpl
- exercises/practice/eliuds-eggs/src/eliuds_eggs.clj
- exercises/practice/eliuds-eggs/test/eliuds_eggs_test.clj
Also
* Update function template in starter file
> eliuds-eggs: Add generators and regenerate tests

- exercises/practice/sieve/.meta/generator.tpl
Forgot to change 'description' to 'context' before merging the previous sieve PR.
> sieve: Fix generator

- exercises/practice/flatten-array/.docs/instructions.append.md
- exercises/practice/flatten-array/.meta/config.json
- exercises/practice/flatten-array/.meta/generator.clj
- exercises/practice/flatten-array/.meta/generator.tpl
- exercises/practice/flatten-array/.meta/tests.toml
- exercises/practice/flatten-array/src/flatten_array.clj
- exercises/practice/flatten-array/test/flatten_array_test.clj
> flatten-array: Update to latest

- exercises/practice/perfect-numbers/.meta/config.json
- exercises/practice/perfect-numbers/.meta/example.clj
- exercises/practice/perfect-numbers/.meta/generator.clj
- exercises/practice/perfect-numbers/.meta/generator.tpl
- exercises/practice/perfect-numbers/.meta/tests.toml
- exercises/practice/perfect-numbers/src/perfect_numbers.clj
- exercises/practice/perfect-numbers/test/perfect_numbers_test.clj
Also replaced the old and slow example solution.
> perfect-numbers: Update to latest

- exercises/practice/robot-simulator/.meta/example.clj
- exercises/practice/robot-simulator/.meta/generator.clj
- exercises/practice/robot-simulator/.meta/generator.tpl
- exercises/practice/robot-simulator/.meta/tests.toml
- exercises/practice/robot-simulator/src/robot_simulator.clj
- exercises/practice/robot-simulator/test/robot_simulator_test.clj
> robot-simulator: Update to latest

- exercises/practice/simple-cipher/.meta/generator.tpl
- exercises/practice/simple-cipher/test/simple_cipher_test.clj
Forum topic: https://forum.exercism.org/t/tests-pass-but-cant-submit/16563
Tests were incorrectly generated, this PR should fix them
@ErikSchierboom Please verify that everything is still okay, and merge right away.
> simple-cipher: Fix generator and regenerate tests

- config.json
https://github.com/exercism/clojure/issues/672
> Reassess exercise difficulties
